# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 670e47353834f0db53e03abd74af9e923628a44fe3b652533af2cc142fe2d1bf01109e2405dcf63c7a81f2a059d21f826e2b0b96612afc0cdd86c42fc6846cb4

test:
  secret_key_base: 15129bc1a2d777d6d460cf0c502a491d17a67c785844c828ef8e15b48d37deab500a468607aadda4a2397c068b966785691eb22c186ebf1ce8759f75c62cd93b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
